/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authorized services
         * @description Returns only services in the principal's scope; PLATFORM_ADMIN may browse across services.
         */
        get: operations["listServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List service-scoped incidents */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /**
         * Get a sanitized incident cockpit projection
         * @description Returns the latest bounded diagnosis, evidence metadata, active approval, and execution. Raw prompts, execution tickets, provider responses, and evidence bodies are deliberately excluded.
         */
        get: operations["getIncidentCockpit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /** Read the immutable incident event timeline */
        get: operations["getIncidentTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /** Read separately authorized redacted evidence snapshots */
        get: operations["listIncidentEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        /**
         * Read one service-scoped redacted evidence snapshot
         * @description The evidence id is bound to the incident id in the same database query.
         */
        get: operations["getIncidentEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/diagnosis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an evidence-backed diagnosis */
        post: operations["startDiagnosis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/approval-requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a diagnosed proposal for approval */
        post: operations["requestApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{requestId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record an independent approval decision */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an explicitly approved proposal */
        post: operations["createExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request probe-backed manual resolution */
        post: operations["requestManualResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search published Runbook knowledge
         * @description Searches only published, service-scoped Runbook chunks. The server owns the embedding input and enforces the result and candidate limits.
         */
        get: operations["searchRunbooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service-scoped Runbook summaries
         * @description Runbook administrators see each Runbook's latest version; other roles see only its latest published version.
         */
        get: operations["listRunbooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbooks/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["RunbookKey"];
            };
            cookie?: never;
        };
        /**
         * List service-scoped Runbook versions
         * @description Runbook administrators can read all lifecycle states; other roles can read published versions only.
         */
        get: operations["listRunbookVersions"];
        put?: never;
        /**
         * Create a Runbook draft
         * @description Creates the stable Runbook identity when the key is absent, or verifies that the supplied service and owner metadata match the existing identity.
         */
        post: operations["createRunbookDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook-versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        /**
         * Get a Runbook version
         * @description Published versions are visible to authorized roles; drafts and retired versions require Runbook administration.
         */
        get: operations["getRunbookVersion"];
        /** Update a Runbook draft */
        put: operations["updateRunbookDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook-versions/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        /**
         * Compare two Runbook versions
         * @description Both versions use one database snapshot. Versions belonging to different Runbooks return 409.
         */
        get: operations["diffRunbookVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook-versions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review a Runbook draft
         * @description A review is recorded for the authenticated administrator; no request body is accepted.
         */
        post: operations["reviewRunbookVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runbook-versions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a reviewed Runbook version
         * @description Publishing freezes the definition and its indexed knowledge chunks.
         */
        post: operations["publishRunbookVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/alertmanager/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a validated Alertmanager v4 webhook
         * @description Requires a bearer token with the sentinelops-api audience outside the Demo profile. The isolated Demo profile permits this private-network webhook without a user role.
         */
        post: operations["receiveAlertmanagerWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read append-only audit records
         * @description PLATFORM_ADMIN may read across services. AUDITOR must provide an assigned serviceId. Results use a stable occurredAt/id keyset cursor and contain only structured, allowlisted metadata.
         */
        get: operations["listAuditRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List persisted Eval run summaries
         * @description Returns only summary fields and aggregate metrics; only PLATFORM_ADMIN principals may read Eval runs.
         */
        get: operations["listEvalRunSummaries"];
        put?: never;
        /**
         * Run the reproducible AI evaluation dataset
         * @description Starts a persisted, reproducible evaluation run using the frozen dataset, model identity, prompt, toolset, and Runbook corpus snapshot. Only PLATFORM_ADMIN principals may create an evaluation run.
         */
        post: operations["createEvalRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Immutable evaluation run identifier. */
                id: components["parameters"]["EvalRunId"];
            };
            cookie?: never;
        };
        /**
         * Read a persisted AI evaluation run
         * @description Returns the immutable run configuration, aggregate metrics, case scores, and baseline comparison.
         */
        get: operations["getEvalRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditPage: {
            items: components["schemas"]["AuditRecord"][];
            nextCursor: string | null;
        };
        AuditRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            serviceId: string | null;
            /** @enum {string} */
            actorType: "user" | "service" | "system" | "model";
            actorId: string;
            action: string;
            resourceType: string;
            resourceId: string;
            /** @enum {string} */
            result: "success" | "failure" | "denied" | "unknown";
            beforeHash: string | null;
            afterHash: string | null;
            metadata: {
                [key: string]: unknown;
            };
            traceId: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        ServiceSummary: {
            /** Format: uuid */
            id: string;
            serviceKey: string;
            displayName: string;
            ownerTeam: string;
        };
        RunbookSummary: {
            /** Format: uuid */
            id: string;
            runbookKey: string;
            /** Format: uuid */
            serviceId: string;
            serviceKey: string;
            displayName: string;
            ownerTeam: string;
            /** Format: uuid */
            latestVersionId: string;
            /** Format: int32 */
            latestVersionNumber: number;
            /** @enum {string} */
            lifecycle: "draft" | "published" | "retired";
            riskLevel: components["schemas"]["RiskLevel"];
        };
        /** @enum {string} */
        PlatformRole:
            | "OBSERVER"
            | "ON_CALL_OPERATOR"
            | "SRE_APPROVER"
            | "RUNBOOK_ADMIN"
            | "PLATFORM_ADMIN";
        /** @enum {string} */
        IncidentStatus:
            | "DETECTED"
            | "TRIAGING"
            | "DIAGNOSED"
            | "AWAITING_APPROVAL"
            | "EXECUTING"
            | "VERIFYING"
            | "RESOLVED"
            | "SUPPRESSED"
            | "ESCALATED";
        /** @enum {string} */
        Severity: "sev1" | "sev2" | "sev3" | "sev4";
        /** @enum {string} */
        RiskLevel: "R0" | "R1" | "R2" | "R3";
        /** @enum {string} */
        ApprovalStatus:
            "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED" | "INVALIDATED";
        /** @enum {string} */
        ExecutionStatus:
            | "PENDING"
            | "RUNNING"
            | "VERIFYING"
            | "SUCCEEDED"
            | "FAILED"
            | "UNKNOWN"
            | "ESCALATED";
        /** @enum {string} */
        ApprovalDecision: "approve" | "reject";
        DraftInput: {
            /** Format: uuid */
            serviceId: string;
            displayName: string;
            ownerTeam: string;
            definition: components["schemas"]["RunbookDefinition"];
            markdown: string;
        };
        DraftContent: {
            definition: components["schemas"]["RunbookDefinition"];
            markdown: string;
        };
        /** @description The only definition shape currently supported by the executor. The server must also verify that runbookKey matches the URL and stable Runbook identity before accepting it. */
        RunbookDefinition: {
            runbookKey: string;
            /** @enum {string} */
            risk: "R1";
            /** @enum {string} */
            adapterId: "demo-http";
            parameters: components["schemas"]["RunbookParameterSchema"];
            steps: components["schemas"]["RunbookStep"][];
            verification: components["schemas"]["RunbookVerification"];
            rollback: null;
        };
        RunbookParameterSchema: {
            /** @enum {string} */
            type: "object";
            properties: {
                replicas: {
                    /** @enum {string} */
                    type: "integer";
                    minimum: number;
                    maximum: number;
                };
            };
            required: "replicas"[];
            /** @enum {boolean} */
            additionalProperties: false;
        };
        RunbookStep: {
            /** @enum {string} */
            stepId: "recover-one";
            /** @enum {string} */
            operation: "recover_connection_pool";
        };
        RunbookVerification: {
            /** @enum {string} */
            probe: "demo_checkout_health";
            successThreshold: number;
            attempts: number;
            intervalSeconds: number;
        };
        VersionView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runbookId: string;
            runbookKey: string;
            /** Format: uuid */
            serviceId: string;
            displayName: string;
            ownerTeam: string;
            /** Format: int32 */
            versionNumber: number;
            /** @enum {string} */
            lifecycle: "draft" | "published" | "retired";
            /** Format: int64 */
            revision: number;
            definition: components["schemas"]["RunbookDefinition"];
            markdown: string;
            definitionChecksum: string;
            /** Format: uuid */
            authorPrincipalId: string | null;
            /** Format: uuid */
            reviewerPrincipalId: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            canReview: boolean;
        };
        VersionDiff: {
            /** Format: uuid */
            fromVersionId: string;
            /** Format: uuid */
            toVersionId: string;
            definitionChanged: boolean;
            markdownChanged: boolean;
            beforeDefinition: components["schemas"]["RunbookDefinition"];
            afterDefinition: components["schemas"]["RunbookDefinition"];
            beforeMarkdown: string;
            afterMarkdown: string;
        };
        KnowledgeHit: {
            /** @enum {string} */
            source: "runbook";
            runbookKey: string;
            /** Format: uuid */
            runbookVersionId: string;
            /** Format: int32 */
            versionNumber: number;
            /** Format: uuid */
            chunkId: string;
            /** Format: int32 */
            chunkNo: number;
            content: string;
            /** Format: int64 */
            lexicalRank: number | null;
            /** Format: int64 */
            vectorRank: number | null;
            lexicalScore: number | null;
            vectorScore: number | null;
            fusedScore: number;
        };
        EvalRunRequest: {
            /** @description Immutable dataset key to evaluate. */
            datasetKey: string;
            /**
             * Format: uuid
             * @description Optional completed run from the same scoring and policy snapshot.
             */
            baselineRunId: string | null;
        };
        EvalRunSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed";
            provider: string;
            modelName: string;
            /** Format: uuid */
            datasetId: string;
            releaseAllowed: boolean | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            aggregateMetrics: components["schemas"]["EvalAggregateMetrics"];
        };
        EvalRunView: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed";
            provider: string;
            modelName: string;
            /** Format: uuid */
            datasetId: string;
            datasetChecksum: string;
            /** @description Frozen provider, prompt, toolset, corpus, and evaluation configuration snapshot. */
            runConfig: {
                [key: string]: unknown;
            };
            aggregateMetrics: components["schemas"]["EvalAggregateMetrics"];
            /** @description Null while a run is running; false for failed or threshold-rejected runs. */
            releaseAllowed: boolean | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            results: components["schemas"]["EvalCaseResult"][];
            comparison: {
                /** Format: uuid */
                baselineRunId: string;
                metricDeltas: {
                    citationResolvableRate?: number;
                    dangerousActionBlockRate?: number;
                    runbookAccuracy?: number;
                    rootCauseTop3Accuracy?: number;
                    /** Format: int64 */
                    fictionalToolCount?: number;
                } & {
                    [key: string]: unknown;
                };
                changedCaseKeys: string[];
                configurationDifferences: string[];
            } | null;
        };
        EvalCaseResult: {
            /** Format: uuid */
            caseId: string;
            caseKey: string;
            /** @enum {string} */
            status: "passed" | "failed" | "error";
            proposalHash: string | null;
            scores: components["schemas"]["EvalScores"];
            failureCode: string | null;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            latencyMs: number;
            /** Format: int64 */
            costMicros: number;
        };
        EvalScores: {
            citationResolvable: boolean;
            dangerousActionBlocked: boolean;
            runbookCorrect: boolean;
            rootCauseTop3Correct: boolean;
            /** Format: int32 */
            fictionalToolCount: number;
            safetyApplicable: boolean;
            rootCauseApplicable: boolean;
        };
        /** @description Aggregate metrics or a failure snapshot when the run cannot complete. */
        EvalAggregateMetrics: {
            citationResolvableRate?: number;
            dangerousActionBlockRate?: number;
            runbookAccuracy?: number;
            rootCauseTop3Accuracy?: number;
            /** Format: int64 */
            fictionalToolCount?: number;
            /** Format: int64 */
            caseCount?: number;
            /** Format: int64 */
            expectedCaseCount?: number;
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            /** Format: int64 */
            latencyMs?: number;
            /** Format: int64 */
            costMicros?: number;
            costAvailable?: boolean;
            thresholdFailures?: string[];
            failureCode?: string;
        } & {
            [key: string]: unknown;
        };
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance: string;
            errorCode: string;
            traceId: string;
        } & {
            [key: string]: unknown;
        };
        IncidentSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            serviceId: string;
            serviceKey: string;
            title: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["IncidentStatus"];
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            occurrenceCount: number;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        IncidentPage: {
            items: components["schemas"]["IncidentSummary"][];
            nextCursor?: string | null;
        };
        Hypothesis: {
            rank: number;
            statement: string;
            confidence: number;
            evidenceRefs: string[];
        };
        VerificationExpectation: {
            probe: string;
            successThreshold: number;
            attempts: number;
            intervalSeconds: number;
        };
        DiagnosisProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: uuid */
            diagnosisRunId: string;
            summary: string;
            hypotheses: components["schemas"]["Hypothesis"][];
            missingEvidence: string[];
            /** Format: uuid */
            runbookVersionId?: string | null;
            parameters: {
                [key: string]: unknown;
            };
            riskLevel: components["schemas"]["RiskLevel"];
            expectedVerification?:
                components["schemas"]["VerificationExpectation"] | null;
            proposalHash: string;
            /** Format: date-time */
            createdAt: string;
        };
        CockpitDiagnosis: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            diagnosisRunId: string;
            /** Format: int64 */
            incidentVersion: number;
            summary: string;
            hypotheses: components["schemas"]["Hypothesis"][];
            missingEvidence: string[];
            /** Format: uuid */
            runbookVersionId: string | null;
            runbookVersion: number | null;
            runbookKey: string | null;
            runbookName: string | null;
            parameters: {
                [key: string]: unknown;
            };
            riskLevel: components["schemas"]["RiskLevel"];
            expectedVerification:
                components["schemas"]["VerificationExpectation"] | null;
            proposalHash: string;
            /** Format: date-time */
            createdAt: string;
        };
        EvidenceReference: {
            /** Format: uuid */
            id: string;
            sourceType: string;
            sourceRef: string;
            contentHash: string;
            /** Format: date-time */
            capturedAt: string;
            truncated: boolean;
        };
        EvidenceSnapshot: {
            /** Format: uuid */
            id: string;
            sourceType: string;
            sourceRef: string;
            contentHash: string;
            /** Format: date-time */
            capturedAt: string;
            truncated: boolean;
            /**
             * Format: date-time
             * @description Historical window start when recorded; null when unavailable.
             */
            from: string | null;
            /**
             * Format: date-time
             * @description Historical window end when recorded; null when unavailable.
             */
            to: string | null;
            redactionCount: number;
            redactionRules: (
                "json-pointer" | "key-denylist" | "max-depth" | "string-length"
            )[];
            redactedPayload: {
                [key: string]: unknown;
            };
        };
        CockpitApproval: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            proposalId: string;
            proposalHash: string;
            targetAlias: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Format: int64 */
            resourceVersion: number;
            requiredApprovals: number;
            approvals: number;
            rejections: number;
            /** Format: uuid */
            requesterId: string;
            requesterSubject: string;
            requesterDisplayName: string;
            independentApproverRequired: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        CockpitExecution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            proposalId: string;
            /** Format: uuid */
            approvalRequestId: string;
            status: components["schemas"]["ExecutionStatus"];
            targetAlias: string;
            /** Format: int64 */
            fencingToken: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
        };
        IncidentCockpit: {
            incident: components["schemas"]["IncidentSummary"];
            diagnosis: components["schemas"]["CockpitDiagnosis"] | null;
            evidence: components["schemas"]["EvidenceReference"][];
            activeApproval: components["schemas"]["CockpitApproval"] | null;
            latestExecution: components["schemas"]["CockpitExecution"] | null;
        };
        IncidentTimelineItem: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            sequence: number;
            eventType: string;
            actorType: string;
            actorId: string;
            source?: string | null;
            sourceEventId?: string | null;
            /** @description Server-generated allowlisted summary; raw event payloads are never returned. */
            summary: string;
            /** @description Validated distributed trace identifier when the producer supplied one. */
            traceId: string | null;
            evidenceIds: string[];
            /** Format: date-time */
            occurredAt: string;
        };
        IncidentTimelinePage: {
            items: components["schemas"]["IncidentTimelineItem"][];
            nextCursor?: string | null;
        };
        RequestApproval: {
            /** Format: uuid */
            proposalId: string;
        };
        ApprovalDecisionCommand: {
            decision: components["schemas"]["ApprovalDecision"];
            comment?: string;
            proposalHash: string;
        };
        ApprovalCommandResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: uuid */
            proposalId: string;
            proposalHash: string;
            targetAlias: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Format: int64 */
            resourceVersion: number;
            requiredApprovals: number;
            approvals: number;
            rejections: number;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateExecution: {
            /** Format: uuid */
            proposalId: string;
        };
        ExecutionCommandResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: uuid */
            proposalId: string;
            /** Format: uuid */
            approvalRequestId: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Format: int64 */
            fencingToken: number;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        ManualVerificationResult: {
            /** Format: uuid */
            incidentId: string;
            /** @enum {string} */
            status: "verifying";
            /** Format: int64 */
            incidentVersion: number;
        };
    };
    responses: {
        /** @description The request is malformed or contains invalid values. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description A valid bearer token is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The principal lacks the role or service scope. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The command conflicts with the current workflow state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The resource changed after the caller read it. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description A required provider or dependency is temporarily unavailable. */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        IncidentId: string;
        RunbookKey: string;
        RunbookVersionId: string;
        /** @description Immutable evaluation run identifier. */
        EvalRunId: string;
        /** @description Opaque cursor returned by the preceding page. */
        Cursor: string;
        PageSize: number;
        /** @description Quoted resource revision from the most recent ETag. */
        IfMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted resource revision for subsequent If-Match commands. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listServices: {
        parameters: {
            query?: {
                afterKey?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service summaries ordered by service key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                status?: components["schemas"]["IncidentStatus"];
                serviceId?: string;
                severity?: components["schemas"]["Severity"];
                /** @description Opaque cursor returned by the preceding page. */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor-paginated incident page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getIncidentCockpit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service-scoped incident cockpit. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentCockpit"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getIncidentTimeline: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by the preceding page. */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor-paginated event page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentTimelinePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listIncidentEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted evidence snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSnapshot"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getIncidentEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted evidence snapshot and safe redaction metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startDiagnosis: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diagnosis proposal created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisProposal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    requestApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestApproval"];
            };
        };
        responses: {
            /** @description Approval request created. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionCommand"];
            };
        };
        responses: {
            /** @description Decision recorded using server-confirmed state. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    createExecution: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExecution"];
            };
        };
        responses: {
            /** @description Execution accepted for asynchronous dispatch. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    requestManualResolution: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Verification cycle queued; the incident is not yet resolved. */
            202: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualVerificationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    searchRunbooks: {
        parameters: {
            query: {
                serviceId: string;
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published, service-scoped knowledge hits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeHit"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    listRunbooks: {
        parameters: {
            query?: {
                afterKey?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runbook summaries ordered by Runbook key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunbookSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRunbookVersions: {
        parameters: {
            query?: {
                afterVersion?: number;
                limit?: number;
            };
            header?: never;
            path: {
                key: components["parameters"]["RunbookKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runbook versions ordered by version number. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createRunbookDraft: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                key: components["parameters"]["RunbookKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftInput"];
            };
        };
        responses: {
            /** @description Runbook draft created. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getRunbookVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runbook version. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRunbookDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftContent"];
            };
        };
        responses: {
            /** @description Updated Runbook draft. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    diffRunbookVersions: {
        parameters: {
            query: {
                otherVersionId: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Structural Runbook version diff. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDiff"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviewRunbookVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviewed Runbook draft. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    publishRunbookVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted resource revision from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RunbookVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable published Runbook version. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    receiveAlertmanagerWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-SentinelOps-Source"?: string;
                "X-SentinelOps-Event-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Alert accepted and deduplicated into an incident. */
            202: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAuditRecords: {
        parameters: {
            query?: {
                serviceId?: string;
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A service-scoped or administrator audit page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listEvalRunSummaries: {
        parameters: {
            query?: {
                beforeId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UUIDv7 keyset-paginated Eval run summaries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createEvalRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Evaluation run created or returned from an idempotent replay; its status is completed or failed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The requested evaluation dataset or baseline run does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The idempotency key is already running, has been reused with a different request, or the requested baseline is incompatible. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The configured provider is manual-only or evaluation capacity is exhausted. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getEvalRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Immutable evaluation run identifier. */
                id: components["parameters"]["EvalRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted evaluation run view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The requested evaluation run does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
