/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List service-scoped incidents */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /**
         * Get a sanitized incident cockpit projection
         * @description Returns the latest bounded diagnosis, evidence metadata, active approval, and execution. Raw prompts, execution tickets, provider responses, and evidence bodies are deliberately excluded.
         */
        get: operations["getIncidentCockpit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /** Read the immutable incident event timeline */
        get: operations["getIncidentTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        /** Read separately authorized redacted evidence snapshots */
        get: operations["listIncidentEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/diagnosis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an evidence-backed diagnosis */
        post: operations["startDiagnosis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/approval-requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a diagnosed proposal for approval */
        post: operations["requestApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approval-requests/{requestId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record an independent approval decision */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an explicitly approved proposal */
        post: operations["createExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request probe-backed manual resolution */
        post: operations["requestManualResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/alertmanager/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a validated Alertmanager v4 webhook
         * @description Requires a bearer token with the sentinelops-api audience outside the Demo profile. The isolated Demo profile permits this private-network webhook without a user role.
         */
        post: operations["receiveAlertmanagerWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PlatformRole:
            | "OBSERVER"
            | "ON_CALL_OPERATOR"
            | "SRE_APPROVER"
            | "RUNBOOK_ADMIN"
            | "PLATFORM_ADMIN";
        /** @enum {string} */
        IncidentStatus:
            | "DETECTED"
            | "TRIAGING"
            | "DIAGNOSED"
            | "AWAITING_APPROVAL"
            | "EXECUTING"
            | "VERIFYING"
            | "RESOLVED"
            | "SUPPRESSED"
            | "ESCALATED";
        /** @enum {string} */
        Severity: "sev1" | "sev2" | "sev3" | "sev4";
        /** @enum {string} */
        RiskLevel: "R0" | "R1" | "R2" | "R3";
        /** @enum {string} */
        ApprovalStatus:
            "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED" | "INVALIDATED";
        /** @enum {string} */
        ExecutionStatus:
            | "PENDING"
            | "RUNNING"
            | "VERIFYING"
            | "SUCCEEDED"
            | "FAILED"
            | "UNKNOWN"
            | "ESCALATED";
        /** @enum {string} */
        ApprovalDecision: "approve" | "reject";
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance: string;
            errorCode: string;
            traceId: string;
        } & {
            [key: string]: unknown;
        };
        IncidentSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            serviceId: string;
            serviceKey: string;
            title: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["IncidentStatus"];
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            occurrenceCount: number;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        IncidentPage: {
            items: components["schemas"]["IncidentSummary"][];
            nextCursor?: string | null;
        };
        Hypothesis: {
            rank: number;
            statement: string;
            confidence: number;
            evidenceRefs: string[];
        };
        VerificationExpectation: {
            probe: string;
            successThreshold: number;
            attempts: number;
            intervalSeconds: number;
        };
        DiagnosisProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: uuid */
            diagnosisRunId: string;
            summary: string;
            hypotheses: components["schemas"]["Hypothesis"][];
            missingEvidence: string[];
            /** Format: uuid */
            runbookVersionId?: string | null;
            parameters: {
                [key: string]: unknown;
            };
            riskLevel: components["schemas"]["RiskLevel"];
            expectedVerification?:
                components["schemas"]["VerificationExpectation"] | null;
            proposalHash: string;
            /** Format: date-time */
            createdAt: string;
        };
        CockpitDiagnosis: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            diagnosisRunId: string;
            /** Format: int64 */
            incidentVersion: number;
            summary: string;
            hypotheses: components["schemas"]["Hypothesis"][];
            missingEvidence: string[];
            /** Format: uuid */
            runbookVersionId: string | null;
            runbookVersion: number | null;
            runbookKey: string | null;
            runbookName: string | null;
            parameters: {
                [key: string]: unknown;
            };
            riskLevel: components["schemas"]["RiskLevel"];
            expectedVerification:
                components["schemas"]["VerificationExpectation"] | null;
            proposalHash: string;
            /** Format: date-time */
            createdAt: string;
        };
        EvidenceReference: {
            /** Format: uuid */
            id: string;
            sourceType: string;
            sourceRef: string;
            contentHash: string;
            /** Format: date-time */
            capturedAt: string;
            truncated: boolean;
        };
        EvidenceSnapshot: {
            /** Format: uuid */
            id: string;
            sourceType: string;
            sourceRef: string;
            contentHash: string;
            /** Format: date-time */
            capturedAt: string;
            truncated: boolean;
            redactedPayload: {
                [key: string]: unknown;
            };
        };
        CockpitApproval: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            proposalId: string;
            proposalHash: string;
            targetAlias: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Format: int64 */
            resourceVersion: number;
            requiredApprovals: number;
            approvals: number;
            rejections: number;
            /** Format: uuid */
            requesterId: string;
            requesterSubject: string;
            requesterDisplayName: string;
            independentApproverRequired: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        CockpitExecution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            proposalId: string;
            /** Format: uuid */
            approvalRequestId: string;
            status: components["schemas"]["ExecutionStatus"];
            targetAlias: string;
            /** Format: int64 */
            fencingToken: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
        };
        IncidentCockpit: {
            incident: components["schemas"]["IncidentSummary"];
            diagnosis: components["schemas"]["CockpitDiagnosis"] | null;
            evidence: components["schemas"]["EvidenceReference"][];
            activeApproval: components["schemas"]["CockpitApproval"] | null;
            latestExecution: components["schemas"]["CockpitExecution"] | null;
        };
        IncidentTimelineItem: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            sequence: number;
            eventType: string;
            actorType: string;
            actorId: string;
            source?: string | null;
            sourceEventId?: string | null;
            /** @description Server-generated allowlisted summary; raw event payloads are never returned. */
            summary: string;
            /** @description Validated distributed trace identifier when the producer supplied one. */
            traceId: string | null;
            evidenceIds: string[];
            /** Format: date-time */
            occurredAt: string;
        };
        IncidentTimelinePage: {
            items: components["schemas"]["IncidentTimelineItem"][];
            nextCursor?: string | null;
        };
        RequestApproval: {
            /** Format: uuid */
            proposalId: string;
        };
        ApprovalDecisionCommand: {
            decision: components["schemas"]["ApprovalDecision"];
            comment?: string;
            proposalHash: string;
        };
        ApprovalCommandResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: uuid */
            proposalId: string;
            proposalHash: string;
            targetAlias: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Format: int64 */
            resourceVersion: number;
            requiredApprovals: number;
            approvals: number;
            rejections: number;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateExecution: {
            /** Format: uuid */
            proposalId: string;
        };
        ExecutionCommandResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incidentId: string;
            /** Format: uuid */
            proposalId: string;
            /** Format: uuid */
            approvalRequestId: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Format: int64 */
            fencingToken: number;
            /** Format: int64 */
            incidentVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        ManualVerificationResult: {
            /** Format: uuid */
            incidentId: string;
            /** @enum {string} */
            status: "verifying";
            /** Format: int64 */
            incidentVersion: number;
        };
    };
    responses: {
        /** @description The request is malformed or contains invalid values. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description A valid bearer token is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The principal lacks the role or service scope. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The command conflicts with the current workflow state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The incident changed after the caller read it. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        IncidentId: string;
        /** @description Opaque cursor returned by the preceding page. */
        Cursor: string;
        PageSize: number;
        /** @description Quoted incident resource version from the most recent ETag. */
        IfMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted incident resource version for subsequent If-Match commands. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIncidents: {
        parameters: {
            query?: {
                status?: components["schemas"]["IncidentStatus"];
                serviceId?: string;
                severity?: components["schemas"]["Severity"];
                /** @description Opaque cursor returned by the preceding page. */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor-paginated incident page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getIncidentCockpit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service-scoped incident cockpit. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentCockpit"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getIncidentTimeline: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by the preceding page. */
                cursor?: components["parameters"]["Cursor"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A cursor-paginated event page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentTimelinePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listIncidentEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted evidence snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSnapshot"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startDiagnosis: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted incident resource version from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diagnosis proposal created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisProposal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    requestApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted incident resource version from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestApproval"];
            };
        };
        responses: {
            /** @description Approval request created. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted incident resource version from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionCommand"];
            };
        };
        responses: {
            /** @description Decision recorded using server-confirmed state. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    createExecution: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted incident resource version from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExecution"];
            };
        };
        responses: {
            /** @description Execution accepted for asynchronous dispatch. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionCommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    requestManualResolution: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted incident resource version from the most recent ETag. */
                "If-Match": components["parameters"]["IfMatch"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                incidentId: components["parameters"]["IncidentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Verification cycle queued; the incident is not yet resolved. */
            202: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualVerificationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    receiveAlertmanagerWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-SentinelOps-Source"?: string;
                "X-SentinelOps-Event-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Alert accepted and deduplicated into an incident. */
            202: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
