spring:
  application:
    name: sentinelops-demo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SENTINELOPS_DEMO_JWKS_URI:http://localhost:8081/realms/sentinelops/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8082}

sentinelops:
  demo-mode: ${SENTINELOPS_DEMO_MODE:false}
  demo-alert-relay-mode: ${SENTINELOPS_DEMO_ALERT_RELAY_MODE:false}
  demo-alert-relay-url: ${SENTINELOPS_DEMO_ALERT_RELAY_URL:}
  demo-alert-relay-secret: ${SENTINELOPS_WEBHOOK_DEMO_SECRET:}
  security:
    issuer: ${SENTINELOPS_DEMO_ISSUER:http://localhost:8081/realms/sentinelops}
    audience: demo-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,demoFault
